kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "acid-test"
  namespace: "default"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "13"
  numberOfInstances: 1
  enableMasterLoadBalancer: true
  volume:
    size: "10Gi"

  allowedSourceRanges:
    - 0.0.0.0/0
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
